# Generated by Django 4.0.4 on 2022-04-14 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='질문')),
                ('question_category', models.CharField(choices=[('GE', '일반'), ('AC', '계정'), ('ET', '기타')], default='GE', max_length=2, verbose_name='카테고리')),
                ('answer', models.TextField(verbose_name='답변')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('generators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generators_faq', to=settings.AUTH_USER_MODEL)),
                ('last_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_modifier_faq', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
